# .goreleaser.yml
version: 2
project_name: myhome
before:
  hooks:
    - go generate ./internal/myhome/ui/...
    - go generate ./...
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      # FIXME: goreleaser can build for windows and darwin but they are not supported in packaging
      # - windows
      # - darwin
    goarch:
      - amd64
      - arm64
    # id is the name of the snapshot (and of the release) and will be used
    # as the name of the binary. It's also the directory name where the binary
    # will be placed in the archive.
    id: "snapshot"
    dir: .
    main: ./myhome
    ldflags:
      - -X version.Program=myhome
      - -X version.Repo={{.GitURL}}
      - -X version.Version={{if .IsSnapshot}}{{.Summary}}{{else}}{{.Version}}{{end}}
      - -X version.Commit={{.FullCommit}}
