// Code generated by tools/extract-garden-defaults; DO NOT EDIT.
// Source: internal/shelly/scripts/garden.js

package garden

// Garden sprinkler default values extracted from garden.js CONFIG_SCHEMA
const (
	DefaultEarliestStartHour = 3
	DefaultLunchStart        float64 = 12.0
	DefaultLunchEnd          float64 = 14.0
	DefaultEveningStart      float64 = 19.0
	DefaultEveningEnd        float64 = 23.5
	DefaultFallbackStartHour = 5
	DefaultFrostCutoffC      float64 = 2.0
	DefaultRainHoldoffMm     float64 = 8.0
	DefaultMaxDeficitMm      float64 = 25.0
)

// ZoneDefault holds initial per-zone configuration values.
type ZoneDefault struct {
	name        string
	appRateMmH  float64
	kc          float64
	triggerMm   float64
	maxMin      int
	fallbackMin int
	enabled     bool
}

// defaultZoneDefaults mirrors ZONE_DEFAULTS from garden.js.
// Update appRateMmH for each zone after running 'ctl garden calibrate'.
var defaultZoneDefaults = []ZoneDefault{
	{name: "pelouse-maison",   appRateMmH: 12.0, kc: 0.8, triggerMm: 12.0, maxMin: 30, fallbackMin: 15, enabled: true},
	{name: "massifs",          appRateMmH: 18.0, kc: 0.6, triggerMm:  8.0, maxMin: 30, fallbackMin: 15, enabled: true},
	{name: "pelouse-barriere", appRateMmH: 12.0, kc: 0.8, triggerMm: 12.0, maxMin: 30, fallbackMin: 15, enabled: true},
}
