package main

import (
	"fmt"
	"strconv"
	"strings"
)

// GoOptions selects which sections GenerateGo emits into one output file.
// Split because PoolKVSKeys (internal/myhome/shelly/script, package script)
// and the Default* constants (myhome/ctl/pool, package pool) live in two
// different Go packages/modules and must be generated by two separate
// go:generate invocations — see CLAUDE.md's "go generate sub-module gap".
type GoOptions struct {
	Package       string // Go package name for the generated file
	SourceJSON    string // schema JSON path, recorded in the header comment
	Consts        bool   // emit "Default*" constants
	KVSKeys       bool   // emit the KVSKeysVar map
	ZoneFieldKeys bool   // emit the ZoneFieldKeysVar map (garden only)
}

// GenerateGo renders a complete Go source file for schema per opts.
func GenerateGo(schema *Schema, opts GoOptions) (string, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by tools/genconfigschema from %s; DO NOT EDIT.\n", opts.SourceJSON)
	fmt.Fprintf(&b, "// Source of truth: %s (see issue #439).\n\n", opts.SourceJSON)
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)

	needsTime := opts.Consts && usesTimeDuration(schema)
	if needsTime {
		b.WriteString("import \"time\"\n\n")
	}

	if opts.Consts {
		block, err := genConsts(schema)
		if err != nil {
			return "", err
		}
		b.WriteString(block)
	}

	if opts.KVSKeys {
		b.WriteString(genKVSKeysMap(schema.KVSKeysVar, schema.KVSPrefix, schema.Fields))
	}

	if opts.ZoneFieldKeys {
		if schema.ZoneFieldKeysVar == "" {
			return "", fmt.Errorf("ZoneFieldKeys requested but schema has no zoneFieldKeysVar")
		}
		b.WriteString(genZoneFieldKeysMap(schema.ZoneFieldKeysVar, schema.ZoneFields))
	}

	return b.String(), nil
}

func usesTimeDuration(schema *Schema) bool {
	for _, f := range schema.Fields {
		if f.GoConst && f.GoConstType == "time.Duration" {
			return true
		}
	}
	return false
}

func genConsts(schema *Schema) (string, error) {
	var b strings.Builder
	b.WriteString("const (\n")
	for _, f := range schema.Fields {
		if !f.GoConst {
			continue
		}
		name := "Default" + f.GoConstNameOrDefault()
		lit, err := goLiteral(f)
		if err != nil {
			return "", fmt.Errorf("field %q: %w", f.Name, err)
		}
		switch f.GoConstType {
		case "time.Duration":
			fmt.Fprintf(&b, "\t%s = %s * time.Millisecond\n", name, lit)
		case "float64":
			fmt.Fprintf(&b, "\t%s float64 = %s\n", name, lit)
		case "":
			fmt.Fprintf(&b, "\t%s = %s\n", name, lit)
		default:
			return "", fmt.Errorf("field %q: unknown goConstType %q", f.Name, f.GoConstType)
		}
	}
	b.WriteString(")\n\n")
	return b.String(), nil
}

// goLiteral renders f.Default as a Go literal matching f.Type.
func goLiteral(f Field) (string, error) {
	switch v := f.Default.(type) {
	case bool:
		if f.Type != "boolean" {
			return "", fmt.Errorf("default %v is bool but type is %q", v, f.Type)
		}
		return strconv.FormatBool(v), nil
	case float64:
		if f.Type != "number" {
			return "", fmt.Errorf("default %v is number but type is %q", v, f.Type)
		}
		if v == float64(int64(v)) {
			return strconv.FormatInt(int64(v), 10), nil
		}
		return strconv.FormatFloat(v, 'g', -1, 64), nil
	case string:
		if f.Type != "string" {
			return "", fmt.Errorf("default %q is string but type is %q", v, f.Type)
		}
		return strconv.Quote(v), nil
	case nil:
		return "", fmt.Errorf("field has no default; goConst cannot be true for a null default")
	default:
		return "", fmt.Errorf("unsupported default value type %T", v)
	}
}

func genKVSKeysMap(varName, prefix string, fields []Field) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s maps configuration field names to KVS keys.\n", varName)
	fmt.Fprintf(&b, "// Key length is validated at generation time (see tools/genconfigschema); the\n")
	fmt.Fprintf(&b, "// KVS prefix is %q.\n", prefix)
	fmt.Fprintf(&b, "var %s = map[string]string{\n", varName)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(f.GoName()), strconv.Quote(f.KVSKey(prefix)))
	}
	b.WriteString("}\n\n")
	return b.String()
}

func genZoneFieldKeysMap(varName string, zoneFields []ZoneField) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s maps per-zone struct field names to their KVS key suffix\n", varName)
	fmt.Fprintf(&b, "// (applied after the \"zoneN-\" per-zone infix), mirroring garden.js's\n")
	fmt.Fprintf(&b, "// ZONE_KEY_SPECS.\n")
	fmt.Fprintf(&b, "var %s = map[string]string{\n", varName)
	for _, zf := range zoneFields {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(zf.Field), strconv.Quote(zf.Key))
	}
	b.WriteString("}\n\n")
	return b.String()
}
