// Code generated by tools/extract-pool-defaults; DO NOT EDIT.
// Source: internal/shelly/scripts/pool-pump.js

package pool

import "time"

// Pool pump default values extracted from pool-pump.js CONFIG_SCHEMA
const (
	DefaultEcoSpeed                = 2
	DefaultMidSpeed                = 1
	DefaultHighSpeed               = 0
	DefaultBootstrapHoursThreshold = 6
	DefaultBootstrapDuration       = 120000 * time.Millisecond
	DefaultNightRunDuration        = 3600000 * time.Millisecond
	DefaultBootstrapToSpeedDelay   = 500 * time.Millisecond
	DefaultTemperatureThreshold    = 20
)
