// Code generated by tools/extract-pool-defaults; DO NOT EDIT.
// Source: internal/shelly/scripts/pool-pump.js

package pool

import "time"

// Pool pump default values extracted from pool-pump.js CONFIG_SCHEMA
const (
	DefaultEcoSpeed             = 2
	DefaultMidSpeed             = 1
	DefaultHighSpeed            = 0
	DefaultNightRunDuration     = 3600000 * time.Millisecond
	DefaultGraceDelay           = 10000 * time.Millisecond
	DefaultTemperatureThreshold = 20
)
