package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"
)

// GardenDefaults holds extracted default values from garden.js CONFIG_SCHEMA and ZONE_DEFAULTS.
type GardenDefaults struct {
	// Global CONFIG_SCHEMA defaults
	EarliestStartHour int
	LunchStart        float64
	LunchEnd          float64
	EveningStart      float64
	EveningEnd        float64
	FallbackStartHour int
	FrostCutoffC      float64
	RainHoldoffMm     float64
	MaxDeficitMm      float64
}

const outputTemplate = `// Code generated by tools/extract-garden-defaults; DO NOT EDIT.
// Source: internal/shelly/scripts/garden.js

package garden

// Garden sprinkler default values extracted from garden.js CONFIG_SCHEMA
const (
	DefaultEarliestStartHour = {{.EarliestStartHour}}
	DefaultLunchStart        float64 = {{printf "%.1f" .LunchStart}}
	DefaultLunchEnd          float64 = {{printf "%.1f" .LunchEnd}}
	DefaultEveningStart      float64 = {{printf "%.1f" .EveningStart}}
	DefaultEveningEnd        float64 = {{printf "%.1f" .EveningEnd}}
	DefaultFallbackStartHour = {{.FallbackStartHour}}
	DefaultFrostCutoffC      float64 = {{printf "%.1f" .FrostCutoffC}}
	DefaultRainHoldoffMm     float64 = {{printf "%.1f" .RainHoldoffMm}}
	DefaultMaxDeficitMm      float64 = {{printf "%.1f" .MaxDeficitMm}}
)

// ZoneDefault holds initial per-zone configuration values.
type ZoneDefault struct {
	name        string
	appRateMmH  float64
	kc          float64
	triggerMm   float64
	maxMin      int
	fallbackMin int
	enabled     bool
}

// defaultZoneDefaults mirrors ZONE_DEFAULTS from garden.js.
// Update appRateMmH for each zone after running 'ctl garden calibrate'.
var defaultZoneDefaults = []ZoneDefault{
	{name: "pelouse-maison",   appRateMmH: 12.0, kc: 0.8, triggerMm: 12.0, maxMin: 30, fallbackMin: 15, enabled: true},
	{name: "massifs",          appRateMmH: 18.0, kc: 0.6, triggerMm:  8.0, maxMin: 30, fallbackMin: 15, enabled: true},
	{name: "pelouse-barriere", appRateMmH: 12.0, kc: 0.8, triggerMm: 12.0, maxMin: 30, fallbackMin: 15, enabled: true},
}
`

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <input-js-file> <output-go-file>\n", os.Args[0])
		os.Exit(1)
	}

	inputFile  := os.Args[1]
	outputFile := os.Args[2]

	content, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", inputFile, err)
		os.Exit(1)
	}

	defaults, err := extractDefaults(string(content))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error extracting defaults: %v\n", err)
		os.Exit(1)
	}

	tmpl, err := template.New("defaults").Parse(outputTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output dir: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating %s: %v\n", outputFile, err)
		os.Exit(1)
	}
	defer f.Close()

	if err := tmpl.Execute(f, defaults); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s from %s\n", outputFile, inputFile)
}

func extractDefaults(content string) (*GardenDefaults, error) {
	d := &GardenDefaults{}
	var err error

	d.EarliestStartHour, err = extractIntDefault(content, "earliestStartHour")
	if err != nil {
		return nil, fmt.Errorf("earliestStartHour: %w", err)
	}
	d.LunchStart, err = extractFloatDefault(content, "lunchStart")
	if err != nil {
		return nil, fmt.Errorf("lunchStart: %w", err)
	}
	d.LunchEnd, err = extractFloatDefault(content, "lunchEnd")
	if err != nil {
		return nil, fmt.Errorf("lunchEnd: %w", err)
	}
	d.EveningStart, err = extractFloatDefault(content, "eveningStart")
	if err != nil {
		return nil, fmt.Errorf("eveningStart: %w", err)
	}
	d.EveningEnd, err = extractFloatDefault(content, "eveningEnd")
	if err != nil {
		return nil, fmt.Errorf("eveningEnd: %w", err)
	}
	d.FallbackStartHour, err = extractIntDefault(content, "fallbackStartHour")
	if err != nil {
		return nil, fmt.Errorf("fallbackStartHour: %w", err)
	}
	d.FrostCutoffC, err = extractFloatDefault(content, "frostCutoffC")
	if err != nil {
		return nil, fmt.Errorf("frostCutoffC: %w", err)
	}
	d.RainHoldoffMm, err = extractFloatDefault(content, "rainHoldoffMm")
	if err != nil {
		return nil, fmt.Errorf("rainHoldoffMm: %w", err)
	}
	d.MaxDeficitMm, err = extractFloatDefault(content, "maxDeficitMm")
	if err != nil {
		return nil, fmt.Errorf("maxDeficitMm: %w", err)
	}

	return d, nil
}

func extractIntDefault(content, fieldName string) (int, error) {
	pattern := fmt.Sprintf(`%s:\s*\{[^}]*default:\s*(\d+)`, regexp.QuoteMeta(fieldName))
	re := regexp.MustCompile(pattern)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return 0, fmt.Errorf("not found")
	}
	return strconv.Atoi(strings.TrimSpace(matches[1]))
}

func extractFloatDefault(content, fieldName string) (float64, error) {
	pattern := fmt.Sprintf(`%s:\s*\{[^}]*default:\s*([\d.]+)`, regexp.QuoteMeta(fieldName))
	re := regexp.MustCompile(pattern)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return 0, fmt.Errorf("not found")
	}
	return strconv.ParseFloat(strings.TrimSpace(matches[1]), 64)
}
