package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"
)

// PoolDefaults represents the extracted default values from pool-pump.js
type PoolDefaults struct {
	EcoSpeed             int
	MidSpeed             int
	HighSpeed            int
	NightRunDurationMs   int
	GraceDelayMs         int
	TemperatureThreshold float64
}

const outputTemplate = `// Code generated by tools/extract-pool-defaults; DO NOT EDIT.
// Source: internal/shelly/scripts/pool-pump.js

package pool

import "time"

// Pool pump default values extracted from pool-pump.js CONFIG_SCHEMA
const (
	DefaultEcoSpeed             = {{.EcoSpeed}}
	DefaultMidSpeed             = {{.MidSpeed}}
	DefaultHighSpeed            = {{.HighSpeed}}
	DefaultNightRunDuration     = {{.NightRunDurationMs}} * time.Millisecond
	DefaultGraceDelay           = {{.GraceDelayMs}} * time.Millisecond
	DefaultTemperatureThreshold = {{.TemperatureThreshold}}
)
`

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <input-js-file> <output-go-file>\n", os.Args[0])
		os.Exit(1)
	}

	inputFile := os.Args[1]
	outputFile := os.Args[2]

	// Read the JavaScript file
	content, err := os.ReadFile(inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", inputFile, err)
		os.Exit(1)
	}

	// Extract defaults
	defaults, err := extractDefaults(string(content))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error extracting defaults: %v\n", err)
		os.Exit(1)
	}

	// Generate Go code
	tmpl, err := template.New("defaults").Parse(outputTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Ensure output directory exists
	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	// Create output file
	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating %s: %v\n", outputFile, err)
		os.Exit(1)
	}
	defer f.Close()

	// Write generated code
	if err := tmpl.Execute(f, defaults); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s from %s\n", outputFile, inputFile)
}

func extractDefaults(content string) (*PoolDefaults, error) {
	defaults := &PoolDefaults{}

	// Extract each field from CONFIG_SCHEMA
	var err error

	defaults.EcoSpeed, err = extractIntDefault(content, "ecoSpeed")
	if err != nil {
		return nil, fmt.Errorf("ecoSpeed: %w", err)
	}

	defaults.MidSpeed, err = extractIntDefault(content, "midSpeed")
	if err != nil {
		return nil, fmt.Errorf("midSpeed: %w", err)
	}

	defaults.HighSpeed, err = extractIntDefault(content, "highSpeed")
	if err != nil {
		return nil, fmt.Errorf("highSpeed: %w", err)
	}

	defaults.NightRunDurationMs, err = extractIntDefault(content, "nightRunDurationMs")
	if err != nil {
		return nil, fmt.Errorf("nightRunDurationMs: %w", err)
	}

	defaults.GraceDelayMs, err = extractIntDefault(content, "graceDelayMs")
	if err != nil {
		return nil, fmt.Errorf("graceDelayMs: %w", err)
	}

	defaults.TemperatureThreshold, err = extractFloatDefault(content, "temperatureThreshold")
	if err != nil {
		return nil, fmt.Errorf("temperatureThreshold: %w", err)
	}

	return defaults, nil
}

func extractIntDefault(content, fieldName string) (int, error) {
	// Pattern: fieldName: { ... default: <number>, ... }
	pattern := fmt.Sprintf(`%s:\s*\{[^}]*default:\s*(\d+)`, regexp.QuoteMeta(fieldName))
	re := regexp.MustCompile(pattern)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return 0, fmt.Errorf("not found or invalid format")
	}

	value, err := strconv.Atoi(strings.TrimSpace(matches[1]))
	if err != nil {
		return 0, fmt.Errorf("invalid integer: %w", err)
	}

	return value, nil
}

func extractFloatDefault(content, fieldName string) (float64, error) {
	// Pattern: fieldName: { ... default: <number>, ... }
	pattern := fmt.Sprintf(`%s:\s*\{[^}]*default:\s*([\d.]+)`, regexp.QuoteMeta(fieldName))
	re := regexp.MustCompile(pattern)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return 0, fmt.Errorf("not found or invalid format")
	}

	value, err := strconv.ParseFloat(strings.TrimSpace(matches[1]), 64)
	if err != nil {
		return 0, fmt.Errorf("invalid float: %w", err)
	}

	return value, nil
}
