name: auto-tag-minor
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
        'v[0-9]+.x'

jobs:
  tag-minor:
    runs-on: ubuntu-latest
    steps:
        -
            name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
        -
            name: Setup Go
            uses: actions/setup-go@v5
            with:
                go-version: '1.23.x'
        -
            id: go-build
            name: Run go build
            run: go build ./...
        -
            id: go-test
            name: Run go test
            run: go test ./...
        -
            name: Get previous tag
            id: previoustag
            uses: 'WyriHaximus/github-action-get-previous-tag@v1'
            with:
                fallback: 0.0.0 # Optional fallback tag to use when no tag can be found
        -
            name: Get semantic version
            id: semver
            uses: 'WyriHaximus/github-action-next-semvers@v1'
            with:
                version: ${{ steps.previoustag.outputs.tag }}
        -
            name: Add annotated tag (new minor)
            uses: rickstaa/action-create-tag@v1
            id: "tag-minor"
            with:
                tag: v${{ steps.semver.outputs.minor }}
                tag_exists_error: true
                message: "Release v${{ steps.semver.outputs.minor }}"
        -
            name: Trigger Packaging Workflow
            run: |
                curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/actions/workflows/package-deb.yml/dispatches \
                    -d '{"ref":"v${{ steps.semver.outputs.minor }}","inputs":{"previous":"v${{ steps.previoustag.outputs.tag }}","base_ref":"${{ github.base_ref }}"}}'
        