name: on-tag-main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show previous tag
        id: previous-tag
        run: |
          echo "previous=$(git describe --tags --abbrev=0 HEAD^)" | tee -a "$GITHUB_OUTPUT"
      - name: Trigger Packaging Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/package-release.yml/dispatches \
            -d '{"ref":"${{ github.ref }}","inputs":{"previous":"${{ steps.previous-tag.outputs.previous }}"}}'
