name: Package and Release
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    workflow_dispatch:
        inputs:
            previous:
                description: 'Previous tag'
                required: false
            base_ref:
                description: 'Base ref'
                required: false
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    package-deb:
        runs-on: ubuntu-latest
        outputs:
            release_version: ${{ steps.version.outputs.release }}
            deb_file: ${{ steps.build-deb.outputs.file_name }}
        steps:
            -
                name: Install jq
                uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: jq
            -
                name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    ref: ${{ github.event.ref }}
            -
                name: Setup Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.23.x'
            -
                id: go-releaser
                name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v6
                with:
                    # either 'goreleaser' (default) or 'goreleaser-pro'
                    distribution: goreleaser
                    # 'latest', 'nightly', or a semver
                    version: '~> v2'
                    #args: release --rm-dist --clean --snapshot
                    args: release -f .goreleaser.yml --clean --snapshot
                # env:
                #     # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
                #     GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
            -
                name: Show artifacts
                run: echo '${{ steps.go-releaser.outputs.artifacts }}' | jq
            -
                id: version
                name: Get package version from latest (current or prior) tag
                run: |
                    # https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
                    # [epoch:]upstream_version[-debian_revision]
                    #echo "upstream_version=$(git describe | sed -E 's|^v*([0-9]+\.[0-9]+\.[0-9]+)-(.*)$|\1|g')" | tee -a $GITHUB_OUTPUT
                    #echo "debian_revision=$(git describe | sed -E 's|^v*([0-9]+\.[0-9]+\.[0-9]+)-(.*)$|\2|g')" | tee -a $GITHUB_OUTPUT
                    #echo "debian_version=$(git describe | sed -E 's|^v*(.*)$|\1|g')" | tee -a $GITHUB_OUTPUT
                    #echo "::set-output name=release::$(git describe)"
                    echo "release=$(git describe)" | tee -a "$GITHUB_OUTPUT"
            -
                id: prepare-deb
                name: Prepare package content
                run: |
                    # main program
                    mkdir -p .debpkg/usr/bin
                    cp $(echo '${{ steps.go-releaser.outputs.artifacts }}' | jq -r '.[] | select(.name == "myhome") | .path') .debpkg/usr/bin/myhome

                    # systemd script as a shared file
                    mkdir -p .debpkg/usr/share/myhome
                    cp linux/debian/myhome.service .debpkg/usr/share/myhome/myhome.service

                    # create DEBIAN directory if you want to add other pre/post scripts
                    mkdir -p .debpkg/DEBIAN
                    cp linux/debian/postinst.sh .debpkg/DEBIAN/postinst
                    chmod +x .debpkg/DEBIAN/postinst
            -
                id: build-deb
                name: Build Debian Package
                uses: jiro4989/build-deb-action@v4
                with:
                    package: myhome
                    package_root: .debpkg
                    maintainer: Francois-Xavier 'FiX' KOWALSKI <fix.kowalski@gmail.com>
                    # `https://hub.docker.com/r/jiro4989/build-deb-action` wants format like version: refs/tags/v*.*.*
                    version: refs/tags/${{ steps.version.outputs.release }}
                    arch: 'arm64' # optional
                    depends: 'libc6 (>= 2.2.1), systemd' # optional
                    desc: 'MyHome Automation.' # optional
                    homepage: 'https://github.com/asnowfix/home-automation' # optional
            -
                name: Upload MyHome DEB as artifact
                uses: actions/upload-artifact@v4
                with:
                    name: deb_file
                    path: ${{ steps.build-deb.outputs.file_name }}
    package-msi:
        runs-on: windows-latest
        outputs:
            release_version: ${{ steps.version.outputs.release }}
            msi_file: ${{ steps.build-msi.outputs.file_name }}
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    ref: ${{ github.event.ref }}
            - 
                id: go
                name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.23.0
            -
                id: version
                name: Get package version from latest (current or prior) tag
                run: |
                    $tag = git describe
                    Add-Content -Path $env:GITHUB_OUTPUT -Value "release=$tag"
            - 
                id: build
                name: Build Windows Exectutable
                run: go build .\\myhome
            - 
                id: go-msi
                name: Install go-msi
                run: choco install go-msi
            -
                id: build-msi
                name: Build Windows Installer MSI from exe file
                env:
                    Path: "C:\\Program Files\\go-msi"
                run: |
                    echo $env:Path
                    go-msi make --msi MyHome-${{ steps.version.outputs.release }}.msi --version ${{ steps.version.outputs.release }} --path .\wix.json --arch amd64 --license .\LICENSE
                    Add-Content -Path $env:GITHUB_OUTPUT -Value "msi_file=MyHome-${{ steps.version.outputs.release }}.msi"
            -
                name: Upload MyHome MSI as artifact
                uses: actions/upload-artifact@v4
                with:
                    name: msi_file
                    path: ${{ steps.build-msi.outputs.msi_file }}

    release:
        runs-on: ubuntu-latest
        needs:
            - package-deb
            - package-msi
        steps:
            -
                name: Download MyHome MSI from package-msi
                uses: actions/download-artifact@v4
                with:
                    name: msi_file
            -
                name: Download MyHome DEB from package-deb
                uses: actions/download-artifact@v4
                with:
                    name: deb_file
            -
                name: Release
                id: release
                uses: ncipollo/release-action@v1
                with:
                    name: Release ${{ needs.package-deb.outputs.release_version }}
                    artifactErrorsFailBuild: true
                    artifacts: "${{ needs.package-deb.outputs.deb_file }},MyHome-${{ needs.package-deb.outputs.release_version }},README.md"
                    #bodyFile: CHANGELOG.md
                    #tag: ${{ needs.package-deb.outputs.release_version }}-rc${{ github.run_number }}
                    tag: ${{ needs.package-deb.outputs.release_version }}
                    prerelease: false   # beta, rc
                    draft: true         # confirmation in the UI
                    replacesArtifacts: true
                    generateReleaseNotes: true