name: Windows Installer Creation and Publication as Release
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    workflow_dispatch:
        inputs:
            previous:
                description: 'Previous tag'
                required: false
            base_ref:
                description: 'Base ref'
                required: false
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  package-msi:
    runs-on: windows-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.ref }}
      - 
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      -
        id: version
        name: Get package version from latest (current or prior) tag
        run: |
            echo "release=$(git describe)" | tee -a "$GITHUB_OUTPUT"
      - 
        name: Build Windows Exectutable
        run: go build -o myhome.exe ./myhome
      - 
        name: Install go-msi
        run: choco install -y "go-msi"
      -
        id: build-msi
        name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'myhome.exe'
      -
        name: Release
        id: release
        uses: ncipollo/release-action@v1
        with:
            name: Release v${{ steps.version.outputs.release }}
            artifactErrorsFailBuild: true
            artifacts: "${{ steps.build-msi.outputs.file_name }},README.md"
            #bodyFile: CHANGELOG.md
            tag: ${{ steps.version.outputs.release }}-rc${{ github.run_number }}
            prerelease: true
            draft: true
            replacesArtifacts: true
            generateReleaseNotes: true