name: Update PR Description with Commits

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to find common ancestor

      - name: Update PR description with commit list
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            const base = context.payload.pull_request.base.sha;
            const head = context.payload.pull_request.head.sha;
            
            // Get the merge base (common ancestor)
            const { data: comparison } = await github.rest.repos.compareCommits({
              owner,
              repo,
              base,
              head,
            });
            
            // Extract commit messages
            const commits = comparison.commits.map(commit => {
              const message = commit.commit.message.split('\n')[0]; // Get first line (headline)
              const sha = commit.sha.substring(0, 7); // Short SHA
              return `- ${message} (\`${sha}\`)`;
            }).join('\n');
            
            // Get current PR description
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: pr_number,
            });
            
            const currentBody = pr.body || '';
            
            // Check if we already have a commits section
            const commitsMarker = '<!-- AUTO-GENERATED-COMMITS -->';
            const commitsHeader = '\n\n## Commits\n\n';
            const commitsFooter = '\n<!-- END-AUTO-GENERATED-COMMITS -->';
            
            let newBody;
            if (currentBody.includes(commitsMarker)) {
              // Replace existing commits section
              const regex = new RegExp(
                `${commitsMarker}[\\s\\S]*?<!-- END-AUTO-GENERATED-COMMITS -->`,
                'g'
              );
              newBody = currentBody.replace(
                regex,
                `${commitsMarker}${commitsHeader}${commits}${commitsFooter}`
              );
            } else {
              // Append commits section
              newBody = `${currentBody}${commitsMarker}${commitsHeader}${commits}${commitsFooter}`;
            }
            
            // Update PR description
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: pr_number,
              body: newBody,
            });
            
            console.log(`Updated PR #${pr_number} with ${comparison.commits.length} commits`);
