name: Windows Installer Creation and Publication

on: [push]

jobs:
  create-windows-installer:
    runs-on: windows-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - 
        name: Build Windows Exectutable
        run: go build -o myhome.exe ./myhome
      - 
        name: Install go-msi
        run: choco install -y "go-msi"
      -
        name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'myhome.exe'
      -
        run: |
            gh release create v1.2.3 release.tar.xz
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        name: Creates a release in GitHub and uploads attachments
